version: '3'
services:
  base:
    image: node:23
    volumes:
      - reactivities-nodemodules:/usr/src/app/node_modules
      - ./../../../Reactivities.WebClient:/usr/src/app
    working_dir: /usr/src/app

  reactivities-webclient-install:
    extends:
      service: base
    command: npm i
  reactivities-webclient-build:
    extends:
      service: base
    command: npm run build
  reactivities-webclient-create-bundles:
    extends:
      service: base
    command: npm run create-bundles

volumes:
  reactivities-nodemodules:
    external: true

# Based on https://medium.com/hackernoon/a-better-way-to-develop-node-js-with-docker-cd29d3a0093