version: '3'
services:
  reactivities-webclient-npm:
    image: node:23
    volumes:
      - reactivities-nodemodules:/usr/src/app/node_modules
      - ./../../../Reactivities.WebClient:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  reactivities-nodemodules:
    external: true

# Based on https://medium.com/hackernoon/a-better-way-to-develop-node-js-with-docker-cd29d3a0093