version: '3'
services:
  base:
    image: node:23
    volumes:
      - ./../..:/usr/src/app
    working_dir: /usr/src/app

  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build
  create-bundles:
    extends:
      service: base
    command: npm run create-bundles

# Based on https://medium.com/hackernoon/a-better-way-to-develop-node-js-with-docker-cd29d3a0093