version: '3'
services:
  reactivities-webclient-dev:
    image: node:23
    volumes:
      - reactivities-nodemodules:/usr/src/app/node_modules
      - ./../..:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - 3000:3000
      - 3001:3001

volumes:
  reactivities-nodemodules:
    external: true

# Based on https://medium.com/hackernoon/a-better-way-to-develop-node-js-with-docker-cd29d3a0093